name: Workflow for S3 Deploy - develop

on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Deploy
      uses: reggionick/s3-deploy@v3
      with:
        folder: dist
        bucket: ${{ secrets.S3_BUCKET }}
        dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
        invalidation: /
        delete-removed: true
        no-cache: true
        private: true
        files-to-include: ".*/*,*/*,**"
