name: Run test for angular

on: 
  pull_request:
    types: [opened, synchronize, reopened]
    
jobs: 
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      - name: Node setup
        uses: actions/setup-node@v3
        with: 
          node-version: 16.x
      - name: Install dependencies
        run: npm ci
      - name: Test and coverage
        run: npm run test -- --no-watch --code-coverage --browsers=ChromeHeadlessCI
      - name: Create project directory
        run: mkdir -p /github/workspace/DS2-Univalle/watchQueue
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: DS2-Univalle/watchQueue

